// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKb6rC6eXugh9Civd0nKnY8VuCtjTVvXI',
    appId: '1:447061565088:web:cc19808f2631a58126f3c5',
    messagingSenderId: '447061565088',
    projectId: 'guff-6e92b',
    authDomain: 'guff-6e92b.firebaseapp.com',
    storageBucket: 'guff-6e92b.firebasestorage.app',
    measurementId: 'G-P110BEM43L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8biP8fvnbfTy3Z959KtqR0nnLxnNGBFo',
    appId: '1:447061565088:android:2ae91618dd43c98626f3c5',
    messagingSenderId: '447061565088',
    projectId: 'guff-6e92b',
    storageBucket: 'guff-6e92b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_muzUVZ6QS9MnlXcQzrPgS8pXtNgBPQI',
    appId: '1:447061565088:ios:ddc0764476c1374526f3c5',
    messagingSenderId: '447061565088',
    projectId: 'guff-6e92b',
    storageBucket: 'guff-6e92b.firebasestorage.app',
    iosBundleId: 'com.example.guff',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_muzUVZ6QS9MnlXcQzrPgS8pXtNgBPQI',
    appId: '1:447061565088:ios:ddc0764476c1374526f3c5',
    messagingSenderId: '447061565088',
    projectId: 'guff-6e92b',
    storageBucket: 'guff-6e92b.firebasestorage.app',
    iosBundleId: 'com.example.guff',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKb6rC6eXugh9Civd0nKnY8VuCtjTVvXI',
    appId: '1:447061565088:web:c5aa94760bd8a1a926f3c5',
    messagingSenderId: '447061565088',
    projectId: 'guff-6e92b',
    authDomain: 'guff-6e92b.firebaseapp.com',
    storageBucket: 'guff-6e92b.firebasestorage.app',
    measurementId: 'G-ESS4KZBC15',
  );

}